# NumPy

NumPy is a low level library written in C (and FORTRAN) for high level mathematical functions. NumPy cleverly overcomes the problem of running slower algorithms on Python by using multidimensional arrays and functions that operate on arrays. Any algorithm can then be expressed as a function on arrays, allowing the algorithms ti be run quickly.

## **What is NumPy**

- The fundamental package for scientific computing in Python
- A python Library that provides a multidimensional array objecy, various derived objects

## **What is NumPy Array?**

An array is a grid of valuesand it contains information about the raw data, how to locate an element, and how to interpret an element

1) 1D Array
```
7 2 9 10 
----->
axis 0

shape: (4,) Ie column
``` 

2) 2D Array
```
axis 0|  5.2  3.0  4.5
      |  9.1  0.1  0.3
      < ------->
      axis 1 
      
Shape:(2, 3) Ie rows, column
```

3) 3D Array
```
shape: (4, 3, 2) Ie 4 rows 3 columns 2 depth


## **NumPy VS Python List**

***ADVANTAGES of using NumPy arrays over python list***

- consume less memory
- fast as compared to the python List
- convenient to use

## **Installation & Import NumPy**
!pip install numpy

In [1]:
import numpy as np

In [2]:
# Creating numpy array
arr = np.array([1, 2, 3, 4])
print(arr, type(arr)) # numpy and dimensional array

lst = [1, 2, 3, 4]
print(lst, type(lst))

[1 2 3 4] <class 'numpy.ndarray'>
[1, 2, 3, 4] <class 'list'>


## **Importance of NumPy in Python**

- Wide variety of mathematical operations on arrays.
- It supplies an enormous library of high-level mathematical functions that operate on these arrays and matrices.
- Mathematical, logical, shape manipulation, sorting, selecting, 1/0, discrete Fourier transforms, basic linear algebra, basic stastical operations, random simulation and much more.

***
***

## NumPy Arrays vs. Python Lists - What is the Difference? 

**Basic Difference**

- Data type storage (List can store heterogenous data where as Numpy Array stores homogenous data type)
- Importing module (List no module or package installation required)
- Numerical operation (List is capable and is less efficient, numpy array works on matrix performance and hence are highly efficient)
- Modification capabilities
- Consumes less memory
- Fast as compared to the python list
- Convenient to use

## Check - Convenient to use

%timeit --> creating one line  
%%timeit --> complete program  

In [3]:
%timeit [j**4 for j in range(1,9)]

2.78 µs ± 46.7 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [4]:
%timeit np.arange(1,9)**4

1.97 µs ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


## Creating NumPy Array / How to create NumPy Array

To create a NumPy Array, we can use the function **np.array()**

In [6]:
a = np.array([1, 2, 3])
print(a)
a

[1 2 3]


array([1, 2, 3])

In [7]:
type(a)

numpy.ndarray

In [9]:
l = []

for i in range(1,5):
    int_1 = int(input("Enter the value: "))
    l.append(int_1)

print(np.array(l))

Enter the value: 325
Enter the value: 436
Enter the value: 3245
Enter the value: 235
[ 325  436 3245  235]


## Dimensions in Array

- 1-D Array  -->   [ 1 2 3 4 ]
- 2-D Array  -->  [[ 1 2 3 4 ]]
- 3-D Array  --> [[[ 1 2 3 4 ]]]
- higher Dimensional Arrays  --> 

## How to identify the dimension of array

To identify the dimension of the array we need to go left to right and count the number of square brackets ie  equivalent to the dimension of the NumPy Array. Practically can be implemented as below

In [10]:
# identifying array dimension
a.ndim

1

In [18]:
arr2 = np.array([[ 1, 2, 3, 4 ], [ 1, 2, 3, 4 ]]) # the size of both list should be same
print(arr2, "\n",arr2.ndim )

[[1 2 3 4]
 [1 2 3 4]] 
 2


In [20]:
arr3 = np.array([1,2,3,4], ndmin = 10) # 10 -d array
print(arr3)
print(arr3.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


## Special NumPy Array

**How to Create NumPy Array using NumPy Function**

- Array filled with 0's
- Array filled with 1's
- Create an empty array
- An array with a range of elements
- Array diagonal element filled with 1's
- create an array with values that are spaced linearly in a specified interval

### Array filled with 0's

In [22]:
# 1-D Array
arr_zero = np.zeros(4) # number of values
print(arr_zero)

# 2-D Array
arr_zero = np.zeros((3,4)) # enter dimensions
print('\n',arr_zero)

[0. 0. 0. 0.]

 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Array filled with 1's

In [24]:
# 1-D Array
arr_one = np.ones(4) # number of values
print(arr_one)

# 2-D Array
arr_one = np.ones((3,4)) # enter dimensions
print('\n',arr_one)

[1. 1. 1. 1.]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### Create an empty array

In [26]:
arr_empty = np.empty(4) # number of values
print(arr_empty)

# 2-D Array
arr_empty = np.empty((3,4)) # enter dimensions
print('\n',arr_empty)

[1. 1. 1. 1.]

 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


### An array with a range of elements

In [29]:
# 1-D Array
arr_rng = np.arange(4) # similar to range in for loop
print(arr_rng)

[0 1 2 3]


### Array diagonal element filled with 1's / Identity matrix

In [31]:
arr_dia = np.eye(3, 5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


### Create an array with values that are spaced linearly in a specified interval

In [32]:
# Linspace : craetes an array with gap

arr_gap = np.linspace(1,10, num=5)
print(arr_gap)

[ 1.    3.25  5.5   7.75 10.  ]


In [33]:
arr_gap = np.linspace(0,10, num=5)
print(arr_gap)

[ 0.   2.5  5.   7.5 10. ]


In [34]:
arr_gap = np.linspace(0,20, num=5)
print(arr_gap)

[ 0.  5. 10. 15. 20.]


## How to Create NumPy Arrays with Random Numbers

1) rand(): the function is used to generate a random value between 0 to 1  
2) randn(): the function is used to generate a random value close to zero. This may return positive or negative numbers as well  
3) ranf(): the function for doing random sampling in numpy. It returns an array of specified shape and fills it with random floats in the half-open intervals [0.0, 1.0) ie   1.0 is excluded
4) randint(): the function is used to generate a random number between a given range  

In [36]:
import random 

### rand()

In [37]:
var = np.random.rand(2) # the value entered is the dimension of the array

print(var)
print()
print(type(var))

[0.66390735 0.66131545]

<class 'numpy.ndarray'>


In [38]:
var1 = np.random.rand(2,4)

print(var1)

[[0.12318129 0.81151948 0.03865923 0.83404868]
 [0.48712537 0.36527129 0.84649903 0.05349253]]


### randn()

In [39]:
var2 = np.random.randn(5)

print(var2)

[-0.46332473 -0.67525217  1.03331865  1.17361576 -0.43132682]


### ranf()

In [40]:
var3 = np.random.ranf(4)
print(var3)

[0.13539395 0.62447255 0.44262335 0.48918315]


### randint()

In [42]:
# raandint(min, max, total_values)

var4 = np.random.randint(5, 20, 5)
print(var4)

[19 12 16  8 16]


## What is Data Type of NumPy Array?